/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 1u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 1u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 1u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 1u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_2 */
#define Pin_2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_0_INBUF_ENABLED 0u
#define Pin_2_0_INIT_DRIVESTATE 1u
#define Pin_2_0_INIT_MUXSEL 0u
#define Pin_2_0_INPUT_SYNC 2u
#define Pin_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_0_NUM 0u
#define Pin_2_0_PORT GPIO_PRT10
#define Pin_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_INBUF_ENABLED 0u
#define Pin_2_INIT_DRIVESTATE 1u
#define Pin_2_INIT_MUXSEL 0u
#define Pin_2_INPUT_SYNC 2u
#define Pin_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_NUM 0u
#define Pin_2_PORT GPIO_PRT10
#define Pin_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* vmin1 */
#define vmin1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define vmin1_0_INBUF_ENABLED 0u
#define vmin1_0_INIT_DRIVESTATE 1u
#define vmin1_0_INIT_MUXSEL 0u
#define vmin1_0_INPUT_SYNC 2u
#define vmin1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vmin1_0_NUM 4u
#define vmin1_0_PORT GPIO_PRT9
#define vmin1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define vmin1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define vmin1_DRIVEMODE CY_GPIO_DM_ANALOG
#define vmin1_INBUF_ENABLED 0u
#define vmin1_INIT_DRIVESTATE 1u
#define vmin1_INIT_MUXSEL 0u
#define vmin1_INPUT_SYNC 2u
#define vmin1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vmin1_NUM 4u
#define vmin1_PORT GPIO_PRT9
#define vmin1_SLEWRATE CY_GPIO_SLEW_FAST
#define vmin1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* vmin2 */
#define vmin2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define vmin2_0_INBUF_ENABLED 0u
#define vmin2_0_INIT_DRIVESTATE 1u
#define vmin2_0_INIT_MUXSEL 0u
#define vmin2_0_INPUT_SYNC 2u
#define vmin2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vmin2_0_NUM 1u
#define vmin2_0_PORT GPIO_PRT9
#define vmin2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define vmin2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define vmin2_DRIVEMODE CY_GPIO_DM_ANALOG
#define vmin2_INBUF_ENABLED 0u
#define vmin2_INIT_DRIVESTATE 1u
#define vmin2_INIT_MUXSEL 0u
#define vmin2_INPUT_SYNC 2u
#define vmin2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vmin2_NUM 1u
#define vmin2_PORT GPIO_PRT9
#define vmin2_SLEWRATE CY_GPIO_SLEW_FAST
#define vmin2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* vout1 */
#define vout1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define vout1_0_INBUF_ENABLED 0u
#define vout1_0_INIT_DRIVESTATE 1u
#define vout1_0_INIT_MUXSEL 4u
#define vout1_0_INPUT_SYNC 2u
#define vout1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vout1_0_NUM 3u
#define vout1_0_PORT GPIO_PRT9
#define vout1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define vout1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define vout1_DRIVEMODE CY_GPIO_DM_ANALOG
#define vout1_INBUF_ENABLED 0u
#define vout1_INIT_DRIVESTATE 1u
#define vout1_INIT_MUXSEL 4u
#define vout1_INPUT_SYNC 2u
#define vout1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vout1_NUM 3u
#define vout1_PORT GPIO_PRT9
#define vout1_SLEWRATE CY_GPIO_SLEW_FAST
#define vout1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* vout2 */
#define vout2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define vout2_0_INBUF_ENABLED 0u
#define vout2_0_INIT_DRIVESTATE 1u
#define vout2_0_INIT_MUXSEL 0u
#define vout2_0_INPUT_SYNC 2u
#define vout2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vout2_0_NUM 2u
#define vout2_0_PORT GPIO_PRT9
#define vout2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define vout2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define vout2_DRIVEMODE CY_GPIO_DM_ANALOG
#define vout2_INBUF_ENABLED 0u
#define vout2_INIT_DRIVESTATE 1u
#define vout2_INIT_MUXSEL 0u
#define vout2_INPUT_SYNC 2u
#define vout2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vout2_NUM 2u
#define vout2_PORT GPIO_PRT9
#define vout2_SLEWRATE CY_GPIO_SLEW_FAST
#define vout2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Button */
#define Button_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_0_INBUF_ENABLED 1u
#define Button_0_INIT_DRIVESTATE 0u
#define Button_0_INIT_MUXSEL 0u
#define Button_0_INPUT_SYNC 2u
#define Button_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_0_NUM 4u
#define Button_0_PORT GPIO_PRT0
#define Button_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Button_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_INBUF_ENABLED 1u
#define Button_INIT_DRIVESTATE 0u
#define Button_INIT_MUXSEL 0u
#define Button_INPUT_SYNC 2u
#define Button_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_NUM 4u
#define Button_PORT GPIO_PRT0
#define Button_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* vplus1 */
#define vplus1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define vplus1_0_INBUF_ENABLED 0u
#define vplus1_0_INIT_DRIVESTATE 1u
#define vplus1_0_INIT_MUXSEL 0u
#define vplus1_0_INPUT_SYNC 2u
#define vplus1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vplus1_0_NUM 5u
#define vplus1_0_PORT GPIO_PRT9
#define vplus1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define vplus1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define vplus1_DRIVEMODE CY_GPIO_DM_ANALOG
#define vplus1_INBUF_ENABLED 0u
#define vplus1_INIT_DRIVESTATE 1u
#define vplus1_INIT_MUXSEL 0u
#define vplus1_INPUT_SYNC 2u
#define vplus1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define vplus1_NUM 5u
#define vplus1_PORT GPIO_PRT9
#define vplus1_SLEWRATE CY_GPIO_SLEW_FAST
#define vplus1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_RED */
#define LED_RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_0_INBUF_ENABLED 0u
#define LED_RED_0_INIT_DRIVESTATE 1u
#define LED_RED_0_INIT_MUXSEL 0u
#define LED_RED_0_INPUT_SYNC 2u
#define LED_RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_0_NUM 3u
#define LED_RED_0_PORT GPIO_PRT6
#define LED_RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_INBUF_ENABLED 0u
#define LED_RED_INIT_DRIVESTATE 1u
#define LED_RED_INIT_MUXSEL 0u
#define LED_RED_INPUT_SYNC 2u
#define LED_RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_NUM 3u
#define LED_RED_PORT GPIO_PRT6
#define LED_RED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_GREEN */
#define LED_GREEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_0_INBUF_ENABLED 0u
#define LED_GREEN_0_INIT_DRIVESTATE 1u
#define LED_GREEN_0_INIT_MUXSEL 0u
#define LED_GREEN_0_INPUT_SYNC 2u
#define LED_GREEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_0_NUM 1u
#define LED_GREEN_0_PORT GPIO_PRT7
#define LED_GREEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_GREEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_INBUF_ENABLED 0u
#define LED_GREEN_INIT_DRIVESTATE 1u
#define LED_GREEN_INIT_MUXSEL 0u
#define LED_GREEN_INPUT_SYNC 2u
#define LED_GREEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_NUM 1u
#define LED_GREEN_PORT GPIO_PRT7
#define LED_GREEN_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
