/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Vin */
#define Vin_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Vin_0_INBUF_ENABLED 0u
#define Vin_0_INIT_DRIVESTATE 1u
#define Vin_0_INIT_MUXSEL 0u
#define Vin_0_INPUT_SYNC 2u
#define Vin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Vin_0_NUM 3u
#define Vin_0_PORT GPIO_PRT10
#define Vin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Vin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Vin_DRIVEMODE CY_GPIO_DM_ANALOG
#define Vin_INBUF_ENABLED 0u
#define Vin_INIT_DRIVESTATE 1u
#define Vin_INIT_MUXSEL 0u
#define Vin_INPUT_SYNC 2u
#define Vin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Vin_NUM 3u
#define Vin_PORT GPIO_PRT10
#define Vin_SLEWRATE CY_GPIO_SLEW_FAST
#define Vin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Button */
#define Button_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_0_INBUF_ENABLED 1u
#define Button_0_INIT_DRIVESTATE 0u
#define Button_0_INIT_MUXSEL 0u
#define Button_0_INPUT_SYNC 2u
#define Button_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_0_NUM 4u
#define Button_0_PORT GPIO_PRT0
#define Button_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Button_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_INBUF_ENABLED 1u
#define Button_INIT_DRIVESTATE 0u
#define Button_INIT_MUXSEL 0u
#define Button_INPUT_SYNC 2u
#define Button_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_NUM 4u
#define Button_PORT GPIO_PRT0
#define Button_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* PinAmp */
#define PinAmp_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define PinAmp_0_INBUF_ENABLED 0u
#define PinAmp_0_INIT_DRIVESTATE 0u
#define PinAmp_0_INIT_MUXSEL 0u
#define PinAmp_0_INPUT_SYNC 2u
#define PinAmp_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define PinAmp_0_NUM 3u
#define PinAmp_0_PORT GPIO_PRT9
#define PinAmp_0_SLEWRATE CY_GPIO_SLEW_FAST
#define PinAmp_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define PinAmp_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define PinAmp_INBUF_ENABLED 0u
#define PinAmp_INIT_DRIVESTATE 0u
#define PinAmp_INIT_MUXSEL 0u
#define PinAmp_INPUT_SYNC 2u
#define PinAmp_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define PinAmp_NUM 3u
#define PinAmp_PORT GPIO_PRT9
#define PinAmp_SLEWRATE CY_GPIO_SLEW_FAST
#define PinAmp_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_RED */
#define LED_RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_0_INBUF_ENABLED 0u
#define LED_RED_0_INIT_DRIVESTATE 1u
#define LED_RED_0_INIT_MUXSEL 0u
#define LED_RED_0_INPUT_SYNC 2u
#define LED_RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_0_NUM 3u
#define LED_RED_0_PORT GPIO_PRT6
#define LED_RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_INBUF_ENABLED 0u
#define LED_RED_INIT_DRIVESTATE 1u
#define LED_RED_INIT_MUXSEL 0u
#define LED_RED_INPUT_SYNC 2u
#define LED_RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_RED_NUM 3u
#define LED_RED_PORT GPIO_PRT6
#define LED_RED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_GREEN */
#define LED_GREEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_0_INBUF_ENABLED 0u
#define LED_GREEN_0_INIT_DRIVESTATE 1u
#define LED_GREEN_0_INIT_MUXSEL 0u
#define LED_GREEN_0_INPUT_SYNC 2u
#define LED_GREEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_0_NUM 1u
#define LED_GREEN_0_PORT GPIO_PRT7
#define LED_GREEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_GREEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_GREEN_INBUF_ENABLED 0u
#define LED_GREEN_INIT_DRIVESTATE 1u
#define LED_GREEN_INIT_MUXSEL 0u
#define LED_GREEN_INPUT_SYNC 2u
#define LED_GREEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_GREEN_NUM 1u
#define LED_GREEN_PORT GPIO_PRT7
#define LED_GREEN_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_GREEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
